accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name = 'signup'),
    path('index/', views.index, name = 'index'),
    path('quest/', views.quest, name = 'quest'),
    path('questAdd/', views.questAdd, name = 'questAdd'),
    path('<int:question_id>/', views.detail, name = 'detail'),
    path('<int:question_id>/results/', views.results, name = 'results'),
    path('<int:question_id>/vote/', views.vote, name = 'vote'),  
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy, reverse
from django.views import generic
from .models import Question, Choice
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.contrib.auth.models import User

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

def quest(request):
 #   question_list = Question.objects.order_by('-pub_date')
 #  context = { 'question_list' : question_list }
    context = 'Create the question'
    return render(request,'accounts/quest.html', {'context' : context})

def questAdd(request):
    current_user = request.user
    user_question = request.POST.get('question_text')
    print("quest ",user_question)
#    import pdb
#    pdb.set_trace()
#    question = None
    existing_question = Question.objects.filter(question_text__iexact = user_question)   
    print("exist_qn",existing_question,"count",existing_question.count())   

    if not existing_question:
        question = Question.objects.create(question_text = user_question, pub_date = timezone.now(), user_id =  current_user.id)
        choice_text = request.POST.get('choice_text')
        choices = choice_text.split(",")
        for choice in choices:
            choice = choice.strip()
            print("choices ",choice)
            if not choice.isspace():
                print("choice",choice)
                Choice.objects.create(user_id = current_user.id, choice_text = choice, question_id = question.id, votes = 0)
        return HttpResponseRedirect(reverse('accounts:index'))   

    else:
        question = None
        print("trying to enter same question")
        return render(request, 'accounts/quest.html', {
            'question' : question,
            'error_message' : "You are trying to enter an existing question",
        })         

def index(request):
    question_list = Question.objects.order_by('-pub_date')
    print("q list",question_list)
 #   context = { 'question_list' : question_list }
 #   context = "You are seeing the question list"
    context = { 'question_list' : question_list }
    
    return render(request,'accounts/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    current_user = request.user
    if(current_user.id != question.user_id):
        print("same user")
        return render (request, 'accounts/detail.html', {'question' : question})
    else:
        print("different user")
        return render(request, 'accounts/index.html', {
            'question' : question,
            'error_message' : "You cannot vote for the question you created ",
        })


def results(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    return render(request, 'accounts/results.html', { 'question' : question })

def vote(request, question_id):
#    return HttpResponse(" Voting on question %s " % question_id)
    question = get_object_or_404(Question, pk = question_id)
    try:
        selected_choice = question.choice_set.get(pk = request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'accounts/detail.html', {
            'question' : question,
            'error_message' : "You didnt select a choice. ",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('accounts:results', args = (question.id, )))

accounts/templates/accounts/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><storng>{{ error_message }}</storng></p>{% endif %}
<form action="{% url 'accounts:vote' question.id  %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}"> {{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" vlue="Vote">
</form>

accounts/templates/accounts/index.html
<p><a href="../../home">Home</a></p>

{% if question_list %}
<strong>QUESTION LIST</strong>
<ul>
    {% for question in question_list %}
    <li>
        <a href="{% url 'accounts:detail' question.id %}">{{ question.question_text }}</a> 
    </li>
    {% endfor %}
</ul>

{% else %}
<p>You cannot vote for your question</p>
{% endif %}

accounts/templates/accounts/quest.html
<a href="../../home/"> Home</a>
{% if error_message %}
<h6>{{ error_message }}</h6>
<form action="{% url 'accounts:questAdd' %}" method="POST">
    {% csrf_token %}
    <strong>CREATE QUESTION</strong> <br/>
    <table>
    <tr>
    <td>Enter the Question </td>
    <td><input type="text" name="question_text" required/></td>
    </tr>
    <tr>
    <td>Enter the choices seperated by comma</td>
    <td><input type="text" name="choice_text" required/></td>
    </tr>
    <tr>
    <td><button>Submit</button></td>
    </tr>
    </table>
</form>
{% else %}
<form action="{% url 'accounts:questAdd' %}" method="POST">
        {% csrf_token %}
        <strong>CREATE QUESTION</strong> <br/>
        <table>
        <tr>
        <td>Enter the Question </td>
        <td><input type="text" name="question_text" required/></td>
        </tr>
        <tr>
        <td>Enter the choices seperated by comma</td>
        <td><input type="text" name="choice_text" required/></td>
        </tr>
        <tr>
        <td><button>Submit</button></td>
        </tr>
        </table>
    </form>
{% endif %}

accounts/templates/accounts/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>
        {{ choic.choice_text }} -- {{ choice.votes }}  vote{{ choice.votes|pluralize }}
    </li>
    {% endfor %}
</ul>
<a href="{% url 'accounts:detail' question.id %}"> Vote again ?</a>
<a href="../../../home/"> Home</a>

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'accounts:quest'  %}">Create Question</a></p>
  <p><a href="{% url 'accounts:index' %}">Vote the Question</a></p>
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}